<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
namespace Atlas\Orm\DataSource\BidiBar;

use Atlas\Orm\Table\AbstractTable;

/**
 * @inheritdoc
 */
class BidiBarTable extends AbstractTable
{
    /**
     * @inheritdoc
     */
    public function getName()
    {
        return 'bidibars';
    }

    /**
     * @inheritdoc
     */
    public function getColNames()
    {
        return [
            'bidibar_id',
            'bidifoo_id',
            'name',
        ];
    }

    /**
     * @inheritdoc
     */
    public function getCols()
    {
        return [
            'bidibar_id' => (object) [
                'name' => 'bidibar_id',
                'type' => 'integer',
                'size' => null,
                'scale' => null,
                'notnull' => false,
                'default' => null,
                'autoinc' => true,
                'primary' => true,
            ],
            'bidifoo_id' => (object) [
                'name' => 'bidifoo_id',
                'type' => 'integer',
                'size' => null,
                'scale' => null,
                'notnull' => false,
                'default' => null,
                'autoinc' => false,
                'primary' => false,
            ],
            'name' => (object) [
                'name' => 'name',
                'type' => 'varchar',
                'size' => 10,
                'scale' => null,
                'notnull' => false,
                'default' => null,
                'autoinc' => false,
                'primary' => false,
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function getPrimaryKey()
    {
        return [
            'bidibar_id',
        ];
    }

    /**
     * @inheritdoc
     */
    public function getAutoinc()
    {
        return 'bidibar_id';
    }

    /**
     * @inheritdoc
     */
    public function getColDefaults()
    {
        return [
            'bidibar_id' => null,
            'bidifoo_id' => null,
            'name' => null,
        ];
    }
}
