<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
namespace Atlas\Orm\DataSource\BidiBar;

use Atlas\Orm\Mapper\Record;

/**
 * @property mixed $bidibar_id INTEGER NULL
 * @property mixed $bidifoo_id INTEGER NULL
 * @property mixed $name VARCHAR(10) NULL
 */
class BidiBarFields extends Record
{
}
